src/proj/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from hello_world.views import hello_world

from reference_book import views
from user_profile import auth_view
from user_profile import views as user_views
from books import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('author/create/', views.CreateAuthorView.as_view(), name='author-create'),
    path('author/update/<int:pk>/', views.UpdateAuthorView.as_view(), name='author-update'),
    path('author/', views.ShowAuthorListView.as_view()),
    path('author/delete/<int:pk>/', views.DeleteAuthorView.as_view(), name='author-delete'),
    path('author/<int:pk>/', views.ShowAuthorByPKView.as_view(), name='author-view'),
    path('serie/create/', views.CreateSerieView.as_view(), name='serie-create'),
    path('serie/update/<int:pk>/', views.UpdateSerieView.as_view(), name='serie-update'),
    path('serie/delete/<int:pk>/', views.DeleteSerieView.as_view(), name='serie-delete'),
    path('serie/<int:pk>/', views.ShowSerieByPKView.as_view(), name='serie-view'),
    path('serie/', views.ShowSerieListView.as_view()),
    path('genre/', views.ShowGenreListView.as_view()),
    path('genre/create/', views.CreateGenreView.as_view(), name='genre-create'),
    path('genre/update/<int:pk>/', views.UpdateGenreView.as_view(), name='genre-update'),
    path('genre/delete/<int:pk>/', views.DeleteGenreView.as_view(), name='genre-delete'),
    path('genre/<int:pk>/', views.ShowGenreByPKView.as_view(), name='genre-view'),
    path('publisher/<int:pk>/', views.ShowPublisherByPKView.as_view(), name='publisher-view'),
    path('publisher/', views.ShowPublishereListView.as_view()),
    path('publisher/create/', views.CreatePublisherView.as_view(), name='publisher-create'),
    path('publisher/update/<int:pk>/', views.UpdatePublisherView.as_view(), name='publisher-update'),
    path('publisher/delete/<int:pk>/', views.DeletePublisherView.as_view(), name='publisher-delete'),
    path('book/<int:pk>/', v.ShowBookByPKView.as_view(), name='book-view'),
    path('book/', v.ShowBookListView.as_view()),
    path('book/create/', v.CreateBookView.as_view(), name="book-create"),
    path('book/update/<int:pk>/', v.UpdateBookView.as_view(), name='book-update'),
    path('book/delete/<int:pk>/', v.DeleteBookView.as_view(), name='book-delete'),
    path('auth_login/', auth_view.MyLoginView.as_view(), name= 'login'),
    path('logout/', auth_view.MyLogOutView.as_view(), name='logout'),
    path('usercreate/', auth_view.CreateUserView.as_view(), name='user_create'),
    path('cart/', include('orders.urls', namespace='orders')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('order/', include('conf_order.urls', namespace='conf_order')),
    path('', views.ShowRefBooksView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name = 'profile'
urlpatterns = [
    path('', views.ProfileView.as_view(), name='user_profile'),
    path('<int:pk>/update/', views.UpdateProfileView.as_view(), name='user_update'),
]

src/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, 
        on_delete=models.CASCADE,
        related_name='profile'
        )

    first_name = models.CharField(
        'Имя',
        max_length=50,
        blank=True,
        null=True,
    )

    last_name = models.CharField(
        'Фамилия',
        max_length=50,
        blank=True,
        null=True
    )

    password = models.CharField(
        'Пароль',
        max_length=50
    )

    email = models.EmailField(
        'Email',
        max_length=50
    )

    phone_number = models.CharField(
        verbose_name='Номер телефона', 
        max_length=20
    )

    country = models.CharField(
        verbose_name='Страна', 
        max_length=100, 
        blank=True,
        null=True
    )

    city = models.CharField(
        verbose_name='Город', 
        max_length=50, 
        blank=True,
        null=True
    )

    zip_code = models.IntegerField(
        'Индекс', 
        blank=True,
        null=True
    )

    second_address = models.CharField(
        'Второй адрес', 
        max_length=100, 
        blank=True,
        null=True
    )

    third_address = models.CharField(
        'Третий адрес', 
        max_length=100, 
        blank=True,
        null=True
    )

    additional_information = models.CharField(
        'Дополнительная информация',
        max_length=200,
        blank=True,
        null=True
    )
    
    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        create = UserProfile.objects.create(user=instance)
        create.save()

src/user_profile/forms.py
from django import forms
from user_profile import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = '__all__'

class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = '__all__'

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = '__all__'

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

src/user_profile/views.py
from django.shortcuts import render
from user_profile import forms
from user_profile import models
from django.views.generic import UpdateView, TemplateView, DetailView
from django.http import HttpResponseRedirect


class ProfileView(TemplateView):
    model = models.UserProfile
    template_name = 'user_profile/userprofile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        profile = models.UserProfile.objects.filter(user=user).first()

        if user.first_name:
            profile.first_name = user.first_name

        if user.last_name:
            profile.last_name = user.last_name

        profile.email = user.email

        profile.save()

        context['profile'] = profile
        return context

class UpdateProfileView(UpdateView):
    model = models.UserProfile
    template_name = 'user_profile/userupdate.html'
    fields = (
        'first_name',
        'last_name',
        'email',
        'phone_number',
        'country',
        'city',
        'zip_code',
        'second_address',
        'third_address',
        'additional_information')
    success_url = '/profile'

src/user_profile/templates/user_profile/userprofile.html
{% extends 'customer_base.html' %}
{% load static %}
{% load crispy_forms_filters%}

{% block title %}
Пользователь: {{ user.username }}
{% endblock title %}

{% block body %}
<h1>
{{ user.username }}
<a href="{% url 'profile:user_update' user.profile.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a>
</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        </tr>
        <tr>
            <td>Логин</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>Имя</td>
            <td>{{ user.first_name }}</td>
        </tr>
        <tr>
            <td>Фамилия</td>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{ user.profile.user.email }}</td>
        </tr>
        <tr>
            <td>Номер телефона</td>
            <td>{{ user.profile.phone_number }}</td>
        </tr>
        <tr>
            <td>Страна</td>
            <td>
                {% if user.profile.country %}
                    {{ user.profile.country }}
                {% else %}
                    <a href="{% url 'profile:user_update' user.profile.pk %}">Редактировать</a
                {% endif %} 
            </td>
        </tr>
        <tr>
            <td>Город</td>
            <td>
                {% if user.profile.city %}
                    {{ user.profile.city }}
                {% else %}
                    <a href="{% url 'profile:user_update' user.profile.pk %}">Редактировать</a
                {% endif %} 
            </td>
        </tr>
        <tr>
            <td>Второй адрес</td>
            <td>
                {% if user.profile.second_address  %}
                    {{ user.profile.second_address  }}
                {% else %}
                    <a href="{% url 'profile:user_update' user.profile.pk %}">Редактировать</a
                {% endif %} 
            </td>
        </tr>
        <tr>
            <td>Третий адрес</td>
            <td>
                {% if user.profile.third_address  %}
                    {{ user.profile.third_address }}
                {% else %}
                    <a href="{% url 'profile:user_update' user.profile.pk %}">Редактировать</a
                {% endif %} 
            </td>
        </tr>
         <tr>
            <td>Индекс</td>
            <td>
                {% if user.profile.zip_code  %}
                    {{ user.profile.zip_code }}
                {% else %}
                    <a href="{% url 'profile:user_update' user.profile.pk %}">Редактировать</a
                {% endif %} 
            </td>
        </tr>
         <tr>
            <td>Дополнительная информация</td>
            <td>
                {% if user.profile.additional_information  %}
                    {{ user.profile.additional_information }}
                {% else %}
                    <a href="{% url 'profile:user_update' user.profile.pk %}">Редактировать</a
                {% endif %}
            </td>
            <td>
             {% for foo in profile.user.templates.all %}
                {% if foo.order %}
                    {% for book in foo.books.all %}
                        <th scope="row">{{ foo.order.pk }}</th>
                        <td>{{ book.book.name }}</td>
                        <td>{{ book.price }}</td>
                    {% endfor %}
                {% endif %}
            {% endfor %}
            </td>
        </tr>
        </tbody>
    </table>

        <h4>Мои заказы</h4>
    {% for foo in profile.user.carts.all %}
        {% if foo.order %}
            <table class="table table-hover">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Номер заказа</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Книги</th>
                    <th scope="col">Цена</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">{{ foo.order.id }}</th>
                    <td>{{ foo.order.order_status }}</td>
                    <td>{% for book in foo.products.all %}
                            {{ book.book.book_name }}<br>
                        {% endfor %}</td>
                    <td>{% for book in foo.products.all %}
                            {{ book.price }}<br>
                        {% endfor %}
                        <b>Итого: {{ foo.total_price }}</b><br>
                    </td>
                </tr>

                </tbody>
            </table>
        {% endif %}<br>
    {% endfor %}


{% endblock body %}

src/user_profile/templates/user_profile/userupdate.html
{% extends 'customer_base.html' %}
{% load static %}
{% load crispy_forms_filters%}

{% block title %}
    <title>Обновить данные профиля</title>
{% endblock title %}

{% block body %}
    <h1>Обновить данные профиля</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-danger">Обновить</button>
    </form>
{% endblock body %}