src/orders/urls.py
from django.urls import path
from django.views.generic.base import View

from . import views

app_name = 'orders'
urlpatterns = [
    #path('add/', views.AddProducrToCartView.as_view(), name='add_product'),
    path('delete-book-in-cart/<int:pk>', views.DeleteBookInCart.as_view(), name='book-in-cart-del'),
    path('update-cart', views.CartUpdateView.as_view(), name='cart-update'),
    path('', views.CartView.as_view(), name='cart')
]

src/proj/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from hello_world.views import hello_world

from reference_book import views
from user_profile import auth_view
from user_profile import views as user_views
from books import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('author/create/', views.CreateAuthorView.as_view(), name='author-create'),
    path('author/update/<int:pk>/', views.UpdateAuthorView.as_view(), name='author-update'),
    path('author/', views.ShowAuthorListView.as_view()),
    path('author/delete/<int:pk>/', views.DeleteAuthorView.as_view(), name='author-delete'),
    path('author/<int:pk>/', views.ShowAuthorByPKView.as_view(), name='author-view'),
    path('serie/create/', views.CreateSerieView.as_view(), name='serie-create'),
    path('serie/update/<int:pk>/', views.UpdateSerieView.as_view(), name='serie-update'),
    path('serie/delete/<int:pk>/', views.DeleteSerieView.as_view(), name='serie-delete'),
    path('serie/<int:pk>/', views.ShowSerieByPKView.as_view(), name='serie-view'),
    path('serie/', views.ShowSerieListView.as_view()),
    path('genre/', views.ShowGenreListView.as_view()),
    path('genre/create/', views.CreateGenreView.as_view(), name='genre-create'),
    path('genre/update/<int:pk>/', views.UpdateGenreView.as_view(), name='genre-update'),
    path('genre/delete/<int:pk>/', views.DeleteGenreView.as_view(), name='genre-delete'),
    path('genre/<int:pk>/', views.ShowGenreByPKView.as_view(), name='genre-view'),
    path('publisher/<int:pk>/', views.ShowPublisherByPKView.as_view(), name='publisher-view'),
    path('publisher/', views.ShowPublishereListView.as_view()),
    path('publisher/create/', views.CreatePublisherView.as_view(), name='publisher-create'),
    path('publisher/update/<int:pk>/', views.UpdatePublisherView.as_view(), name='publisher-update'),
    path('publisher/delete/<int:pk>/', views.DeletePublisherView.as_view(), name='publisher-delete'),
    path('book/<int:pk>/', v.ShowBookByPKView.as_view(), name='book-view'),
    path('book/', v.ShowBookListView.as_view()),
    path('book/create/', v.CreateBookView.as_view(), name="book-create"),
    path('book/update/<int:pk>/', v.UpdateBookView.as_view(), name='book-update'),
    path('book/delete/<int:pk>/', v.DeleteBookView.as_view(), name='book-delete'),
    path('auth_login/', auth_view.MyLoginView.as_view(), name= 'login'),
    path('logout/', auth_view.MyLogOutView.as_view(), name='logout'),
    path('usercreate/', auth_view.CreateUserView.as_view(), name='user_create'),
    path('cart/', include('orders.urls', namespace='orders')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('order/', include('conf_order.urls', namespace='conf_order')),
    path('', views.ShowRefBooksView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from reference_book.models import Author, Serie, Genre, Publisher

def upload(inst, filename):
    return f'book_picture/{inst.pk}-{filename}'


class BookCover(models.Model):
    book_cover = models.CharField(
        'Вид обложки',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_cover}'

class BookRestrictions(models.Model):
    book_restrictions = models.CharField(
        'Возрастные ограничения',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_restrictions}'

class BookAvailability(models.Model):
    book_availability = models.CharField(
        'Доступность книги',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_availability}'

class BookRating(models.Model):
    book_rating = models.CharField(
        'Рейтинг книги',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_rating}'

class Book(models.Model):
    book_name = models.CharField(
        'Название книги',
        max_length=100
    )
    book_description = models.TextField(
        'Описание книги',
        blank=True,
        null=True
    )

    book_picture = models.ImageField(
        'Изображение обложки',
        upload_to=upload
    )

    book_price = models.DecimalField(
        'Цена книги(BYN)',
        default=0.0,
        max_digits=10,
        decimal_places=2
    )

    book_year = models.CharField(
        'Год издания',
        max_length=4
    )

    book_pages = models.CharField(
        'Количество страниц',
        max_length=5
    )

    book_cover = models.ForeignKey(
        BookCover,
        verbose_name='Вид обложки',
        on_delete=models.PROTECT,
        related_name='bookcover'
    )

    book_isbn = models.CharField(
        'ISBN',
        max_length=20
    )

    book_weight = models.CharField(
        'Вес в граммах',
        max_length=5
    )

    book_restrictions = models.ForeignKey(
        BookRestrictions,
        verbose_name='Возрастные ограничения',
        on_delete=models.PROTECT,
        related_name='bookrestrictions'
    )

    book_quantity = models.IntegerField(
        'Количество книг в наличии',
        default=0
    )
    
    book_availability = models.ForeignKey(
        BookAvailability,
        verbose_name='Доступность книги',
        on_delete=models.PROTECT,
        related_name='bookavailability'
    )

    book_rating = models.ForeignKey(
        BookRating,
        verbose_name='Рейтинг книги',
        on_delete=models.PROTECT,
        related_name='bookrating'
    )

    book_adding_date = models.DateTimeField(
        verbose_name='Дата внесения в каталог',
        auto_now=False,
        auto_now_add=True
    )

    book_updating_date = models.DateTimeField(
        verbose_name='Дата последнего изменения карточки',
        auto_now=True,
        auto_now_add=False
    )
    
    book_author = models.ManyToManyField(
        Author,
        verbose_name='Автор книги',
        related_name='book'
    )
    
    book_serie = models.ForeignKey(
        Serie,
        verbose_name='Серия книги',
        on_delete=models.PROTECT,
        related_name='book'
    )
    
    book_genre = models.ManyToManyField(
        Genre,
        verbose_name='Жанры',
        related_name='book'
    )
    
    book_publisher = models.ForeignKey(
        Publisher,
        verbose_name='Издательство',
        on_delete=models.PROTECT,
        related_name='book'
    )

    def __str__(self):
        return f'{self.book_name}'

src/reference_book/models.py
from django.db import models
#from books.models import Book

class Author(models.Model):
    author = models.CharField(
        'Имя автора',
        max_length=50
    )

    def __str__(self):
        return f'{self.author}'

class Serie(models.Model):
    series = models.CharField(
        'Название серии',
        max_length=50
    )

    def __str__(self):
        return self.series

class Genre(models.Model):
    genres = models.CharField(
        'Жанр книги',
        max_length=50
    )

    def __str__(self):
        return self.genres

class Publisher(models.Model):
    publisher = models.CharField(
        'Издательство',
        max_length=50
    )

    def __str__(self):
        return self.publisher

src/books/forms.py
from django import forms
from . import models


class CreateBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'
        widgets = {'book_name': forms.TextInput({"placeholder": "Введите название книги"})}

class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'

src/reference_book/forms.py
from django import forms
from . import models


class CreateGenreForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'

class UpdateGenreForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'


    
class CreateAuthorForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'

class UpdateAuthorForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'

class CreateSerieForm(forms.ModelForm):
    class Meta:
        model = models.Serie
        fields = '__all__'

class UpdateSerieForm(forms.ModelForm):
    class Meta:
        model = models.Serie
        fields = '__all__'


class CreatePublisherForm(forms.ModelForm):
    class Meta:
        model = models.Publisher
        fields = '__all__'

class UpdatePublisherForm(forms.ModelForm):
    class Meta:
        model = models.Publisher
        fields = '__all__'

src/books/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, TemplateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Book
from .forms import CreateBookForm, UpdateBookForm
from reference_book.models import Author, Genre, Serie, Publisher

class CreateBookView(LoginRequiredMixin, CreateView):
    model = Book
    form_class = CreateBookForm
    success_url = '/book'
    template_name = 'refs/create_object.html'
    login_url = '/auth_login'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["header"] = "Создать книгу"
        return context
    
class UpdateBookView(LoginRequiredMixin, UpdateView):
    model = Book
    form_class = UpdateBookForm
    success_url = '/book'
    template_name = 'refs/create_object.html'
    login_url = '/auth_login'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["header"] = "Обновить карточку книги"
        return context

class DeleteBookView(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = '/book'
    template_name = 'refs/delete_object.html'
    login_url = '/auth_login'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["header"] = "Удалить книгу"
        key = self.kwargs.get(self.pk_url_kwarg)
        context["obj"] = Book.objects.get(pk=key)
        return context       

class ShowBookByPKView(DetailView):
    template_name = "refs/book.html"
    model = Book
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        key = self.kwargs.get(self.pk_url_kwarg)
        some_book = Book.objects.get(pk=key)
        context["book_obj"] = some_book
        context["author_obj"] = some_book.book_author.all()
        context["genre_obj"] = some_book.book_genre.all()
        return context

class ShowBookListView(ListView):
    template_name = 'refs/book_list.html'
    paginate_by = 10
    model = Book
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["header"] = "Список книг"
        return context

src/reference_book/templates/refs/author.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Карточка автора
{% endblock title %}
{% block body %}
  <h1>Карточка автора</h1> 
  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя автора</th>
            <th scope="col">Количество книг</th>
            <th scope="col">Список книг</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{ obj.pk }}</th>
            <td>{{ obj }}</td>
            <td>{{ book_list|length }}</td>
            <td>
            {% for book in book_list %}
            <a href="/book/{{ book.pk }}">{{ book }}</a><br>
            {% endfor %}
            </td>
            <td>
            {% if user.is_staff %}
                <a href="{% url 'author-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'author-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
            </td>
        </tr>
    </tbody>
    </table>
{% endblock body %} 

src/reference_book/templates/refs/author_list.html
{% extends 'customer_base.html' %}
{% block title %}
{{ header }}
{% endblock title %}

{% block body %}


  <h1>{{ header }}
  {% if user.is_staff %}
  <a class="btn btn-outline-primary btn-lg" href="{% url 'author-create' %}" role="button">{{ task }}</a></button> 
  {% endif %}
  </h1> 
  
  {% include 'navs/paginator.html' %}

  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя автора</th>
            <th scope="col">-</th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list%}
        <tr>
            <th scope="row">{{ obj.pk }}</th>
            <td>{{ obj.author }}</td>
            <td>
            <a href="{% url 'author-view' obj.pk %}" class="btn btn-info"><i class="fab fa-readme"></i></a> 
            {% if user.is_staff %}
                <a href="{% url 'author-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'author-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

{% include 'navs/paginator.html' %}
{% endblock body %}

src/reference_book/templates/refs/book.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Карточка книги
{% endblock title %}
{% block body %}
<h1>Карточка книги
{% if user.is_staff %}
<a href="{% url 'book-update' book_obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
<a href="{% url 'book-delete' book_obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a>
{% endif %}
</h1>
<img src="{{ book_obj.book_picture.url }}" style="width: 14rem;"> 
  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        </tr>
        <tr>
            <th>Название книги</th>
            <td>{{book_obj.book_name}}</td>
        </tr>
        <tr>
            <th>Описание книги</th>
            <td>{{book_obj.book_description}}</td>
        </tr>
        <tr>
            <th>Автор</th>
            <td>{% for author in author_obj%}<a href="/author/{{ author.pk }}">{{author}}{% endfor %}<br></a></td>
        </tr>
        <tr>
            <th>Жанры</th>
            <td>{% for genre in genre_obj%}<a href="/genre/{{ genre.pk }}">{{genre}}</a>{% endfor %}<br></td>
        </tr>
        <tr>
            <th>Серия</th>
            <td><a href="/serie/{{ book_obj.book_serie.pk }}">{{book_obj.book_serie}}</a></td>
        </tr>
        <tr>
            <th>Издатель</th>
            <td><a href="/publisher/{{ book_obj.book_publisher.pk }}">"{{book_obj.book_publisher}}"</a></td>
        </tr>
        <tr>
            <th>Цена книги</th>
            <td>{{book_obj.book_price}} BYN</td>
        </tr>
        <tr>
            <th>Год выпуска книги</th>
            <td>{{book_obj.book_year}}</td>
        </tr>
        <tr>
            <th>Количество страниц</th>
            <td>{{book_obj.book_pages}}</td>
        </tr>
        <tr>
            <th>Вид обложки</th>
            <td>{{book_obj.book_cover}}</td>
        </tr>
        <tr>
            <th>ISBN номер</th>
            <td>{{book_obj.book_isbn}}</td>
        </tr>
        <tr>
            <th>Вес книги, гр.</th>
            <td>{{book_obj.book_weight}}</td>
        </tr>
        <tr>
            <th>Возрастные ограничения</th>
            <td>{{book_obj.book_restrictions}}</td>
        </tr>
        <tr>
            <th>Количество книг в наличии</th>
            <td>{{book_obj.book_quantity}}</td>
        </tr>
        <tr>
            <th>Доступность</th>
            <td>{{book_obj.book_availability}}</td>
        </tr>
        <tr>
            <th>Рейтинг книги</th>
            <td>{{book_obj.book_rating}}</td>
        </tr>
        <tr>
            <th>Дата внесения в каталог</th>
            <td>{{book_obj.book_adding_date}}</td>
        </tr>
        <tr>
            <th>Время последнего изменения карточки</th>
            <td>{{book_obj.book_updating_date}}</td>
        </tr>
    </tbody>
    </table>
<a href="{% url 'orders:cart' %}?book={{ book_obj.pk }}" class="btn btn-success">В корзину</a></td>
{% endblock body %}

src/reference_book/templates/refs/book_list.html
{% extends 'customer_base.html' %}
{% block title %}
{{ header }}
{% endblock title %}


{% block body %}

  <h1>{{ header }} 
  {% if user.is_staff %}
  <a class="btn btn-outline-primary btn-lg" href="{% url 'book-create' %}" role="button">Создать книгу</a></button> 
  {% endif %}
  </h1> 
  {% include 'navs/paginator.html' %}
  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название книги</th>
            <th scope="col">Рейтинг книги</th>
            <th scope="col">Цена, BYN</th>
            <th scope="col">-</th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list%}
        <tr>
            <th scope="row">{{ obj.pk }}</th>
            <td>{{ obj.book_name }}</td>
            <td>{{ obj.book_rating }}</td>
            <td>{{ obj.book_price }}</td>
            <td>
            <a href="{% url 'book-view' obj.pk %}" class="btn btn-info"><i class="fab fa-readme"></i></a> 
            {% if user.is_staff %}
                <a href="{% url 'book-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'book-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a>
            {% endif %}
            <a href="{% url 'orders:cart' %}?book={{ obj.pk }}" class="btn btn-success"><i class="far fa-shopping-cart"></i></a></td>
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% include 'navs/paginator.html' %}
{% endblock body %}

src/reference_book/templates/refs/create_object.html
{% extends 'customer_base.html' %}
{% load crispy_forms_tags %}
{% block title %}
{{ header }}
{% endblock title %}
{% block body %}
  <h1>{{ header }}</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Подтвердить</button>
    </form>
{% endblock body %} 

src/reference_book/templates/refs/delete_object.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Удаление объекта
{% endblock title %}
{% block body %}
    <h1>{{ header }} {{ obj }} ?</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-danger">Подтвердить</button>
    </form>
{% endblock body %}

src/reference_book/templates/refs/genre.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Карточка жанра
{% endblock title %}
{% block body %}
  <h1>Карточка жанра</h1> 
  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Название жанра</th>
            <th scope="col">Количество книг данного жанра</th>
            <th scope="col">Список книг данного жанра</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ obj }}</td>
            <td>{{ book_list|length }}</td>
            <td>
            {% for book in book_list %}
            <a href="/book/{{ book.pk }}">{{ book }}</a><br>
            {% endfor %}
            </td>
            <td>
            {% if user.is_staff %}
                <a href="{% url 'genre-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'genre-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
            </td>
        </tr>
    </tbody>
    </table>
{% endblock body %} 

src/reference_book/templates/refs/genre_list.html
{% extends 'customer_base.html' %}
{% block title %}
{{ header }}
{% endblock title %}

{% block body %}
  <h1>{{ header }}
  {% if user.is_staff %}
      <a class="btn btn-outline-primary btn-lg" href="{% url 'genre-create' %}" role="button">{{ task }}</a></button> 
  {% endif %}
  </h1> 

  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название жанра</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list%}
        <tr>
            <th scope="row">{{ obj.pk }}</th>
            <td>{{ obj.genres }}</td>
            <td>
            <a href="{% url 'genre-view' obj.pk %}" class="btn btn-info"><i class="fab fa-readme"></i></a> 
            {% if user.is_staff %}
                <a href="{% url 'genre-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'genre-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock body %}

src/reference_book/templates/refs/main.html
{% extends 'customer_base.html' %}
{% block title %}
Главная страница
{% endblock title %}
{% block body %}
<h1>Новинки</h1>
<div class="row">
{% for book in new_books %}
  <div class="col-sm-2">
    <div class="card" style="width: 11rem;">
      <img src="{{ book.book_picture.url }}" class="card-img-top" alt="No picture found">
      <div class="card-body">
        <h5 class="card-title"><a href="/book/{{ book.pk }}">{{ book.book_name}}</a></h5>
        <p class="card-text">{{ book.book_price }} BYN</p>
        <a href="{% url 'orders:cart' %}?book={{ book.pk }}" class="btn btn-primary">Добавить в корзину</a>
      </div>
    </div>
  </div>
{% endfor %}<br>
</div>

<h1>Самые популярные</h1>
<div class="row">
{% for book in top_books%}
  <div class="col-sm-3">
    <div class="card" style="width: 14rem;">
      <img src="{{ book.book_picture.url }}" class="card-img-top" alt="No picture found">
      <div class="card-body">
        <h5 class="card-title"><a href="/book/{{ book.pk }}">{{ book.book_name}}</a></h5>
        <p class="card-text">{{ book.book_price }} BYN</p>
        <a href="{% url 'orders:cart' %}?book={{ book.pk }}" class="btn btn-primary">Добавить в корзину</a>
      </div>
    </div>
  </div>
{% endfor %}
</div>


{% endblock body %} 

src/reference_book/templates/refs/publisher.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Карточка издательства
{% endblock title %}
{% block body %}
  <h1>Карточка издательства</h1> 
  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Название издательства</th>
            <th scope="col">Количество книг данного издательства</th>
            <th scope="col">Список книг данного издательства</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ obj }}</td>
            <td>{{ book_list|length }}</td>
            <td>
            {% for book in book_list %}
            <a href="/book/{{ book.pk }}">{{ book }}</a><br>
            {% endfor %}
            </td>
            <td>
            {% if user.is_staff %}
                <a href="{% url 'publisher-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'publisher-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
            </td>
        </tr>
    </tbody>
    </table>
{% endblock body %} 

src/reference_book/templates/refs/publisher_list.html
{% extends 'customer_base.html' %}
{% block title %}
{{ header }}
{% endblock title %}

{% block body %}
  <h1>{{ header }}
  {% if user.is_staff %}
      <a class="btn btn-outline-primary btn-lg" href="{% url 'publisher-create' %}" role="button">{{ task }}</a></button>
  {% endif %} 
  </h1> 

  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название издательства</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list%}
        <tr>
            <th scope="row">{{ obj.pk }}</th>
            <td>
            <a href="{% url 'publisher-view' obj.pk %}">{{ obj.publisher }}</a></td>
            <td>
            <a href="{% url 'publisher-view' obj.pk %}" class="btn btn-info"><i class="fab fa-readme"></i></a> 
            {% if user.is_staff %}
                <a href="{% url 'publisher-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'publisher-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock body %}

src/reference_book/templates/refs/refbook_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ list_name }}</h1>
    <h2><a href={{ link }}>{{ header }}</a></h2>
    {% for obj in object_list%}
    <a href="/{{ obj_name }}/{{ obj.pk }}"> {{ obj }}</a><br>
    {% endfor %}
</body>
</html>

src/reference_book/templates/refs/serie.html
{% extends 'customer_base.html' %}
{% load static %}
{% block title %}
Карточка серии
{% endblock title %}
{% block body %}
  <h1>Карточка серии</h1> 
  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Названиа серии</th>
            <th scope="col">Количество книг данной серии</th>
            <th scope="col">Список книг данной серии</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ obj }}</td>
            <td>{{ book_list|length }}</td>
            <td>
            {% for book in book_list %}
            <a href="/book/{{ book.pk }}">{{ book }}</a><br>
            {% endfor %}
            </td>
            <td>
            {% if user.is_staff %}
                <a href="{% url 'serie-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'serie-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}
            </td>
        </tr>
    </tbody>
    </table>
{% endblock body %} 

src/reference_book/templates/refs/serie_list.html
{% extends 'customer_base.html' %}
{% block title %}
{{ header }}
{% endblock title %}

{% block body %}
  <h1>{{ header }}
  {% if user.is_staff %}
      <a class="btn btn-outline-primary btn-lg" href="{% url 'serie-create' %}" role="button">{{ task }}</a></button> 
  {% endif %}
  </h1> 

  <table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Название серии</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list%}
        <tr>
            <th scope="row">{{ obj.pk }}</th>
            <td>{{ obj.series }}</td>
            <td>
            <a href="{% url 'serie-view' obj.pk %}" class="btn btn-info"><i class="fab fa-readme"></i></a> 
            {% if user.is_staff %}
                <a href="{% url 'serie-update' obj.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a> 
                <a href="{% url 'serie-delete' obj.pk %}" class="btn btn-dark"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}    
        </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock body %}