src/conf_order/urls.py
from django.urls import path
from conf_order.views import CreateOrderView

app_name = 'conf_order'
urlpatterns = [
    path('create/', CreateOrderView.as_view(), name='create_order'),
]

src/orders/urls.py
from django.urls import path
from django.views.generic.base import View

from . import views

app_name = 'orders'
urlpatterns = [
    #path('add/', views.AddProducrToCartView.as_view(), name='add_product'),
    path('delete-book-in-cart/<int:pk>', views.DeleteBookInCart.as_view(), name='book-in-cart-del'),
    path('update-cart', views.CartUpdateView.as_view(), name='cart-update'),
    path('', views.CartView.as_view(), name='cart')
]

src/proj/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from hello_world.views import hello_world

from reference_book import views
from user_profile import auth_view
from user_profile import views as user_views
from books import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('author/create/', views.CreateAuthorView.as_view(), name='author-create'),
    path('author/update/<int:pk>/', views.UpdateAuthorView.as_view(), name='author-update'),
    path('author/', views.ShowAuthorListView.as_view()),
    path('author/delete/<int:pk>/', views.DeleteAuthorView.as_view(), name='author-delete'),
    path('author/<int:pk>/', views.ShowAuthorByPKView.as_view(), name='author-view'),
    path('serie/create/', views.CreateSerieView.as_view(), name='serie-create'),
    path('serie/update/<int:pk>/', views.UpdateSerieView.as_view(), name='serie-update'),
    path('serie/delete/<int:pk>/', views.DeleteSerieView.as_view(), name='serie-delete'),
    path('serie/<int:pk>/', views.ShowSerieByPKView.as_view(), name='serie-view'),
    path('serie/', views.ShowSerieListView.as_view()),
    path('genre/', views.ShowGenreListView.as_view()),
    path('genre/create/', views.CreateGenreView.as_view(), name='genre-create'),
    path('genre/update/<int:pk>/', views.UpdateGenreView.as_view(), name='genre-update'),
    path('genre/delete/<int:pk>/', views.DeleteGenreView.as_view(), name='genre-delete'),
    path('genre/<int:pk>/', views.ShowGenreByPKView.as_view(), name='genre-view'),
    path('publisher/<int:pk>/', views.ShowPublisherByPKView.as_view(), name='publisher-view'),
    path('publisher/', views.ShowPublishereListView.as_view()),
    path('publisher/create/', views.CreatePublisherView.as_view(), name='publisher-create'),
    path('publisher/update/<int:pk>/', views.UpdatePublisherView.as_view(), name='publisher-update'),
    path('publisher/delete/<int:pk>/', views.DeletePublisherView.as_view(), name='publisher-delete'),
    path('book/<int:pk>/', v.ShowBookByPKView.as_view(), name='book-view'),
    path('book/', v.ShowBookListView.as_view()),
    path('book/create/', v.CreateBookView.as_view(), name="book-create"),
    path('book/update/<int:pk>/', v.UpdateBookView.as_view(), name='book-update'),
    path('book/delete/<int:pk>/', v.DeleteBookView.as_view(), name='book-delete'),
    path('auth_login/', auth_view.MyLoginView.as_view(), name= 'login'),
    path('logout/', auth_view.MyLogOutView.as_view(), name='logout'),
    path('usercreate/', auth_view.CreateUserView.as_view(), name='user_create'),
    path('cart/', include('orders.urls', namespace='orders')),
    path('profile/', include('user_profile.urls', namespace='profile')),
    path('order/', include('conf_order.urls', namespace='conf_order')),
    path('', views.ShowRefBooksView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/user_profile/urls.py
from django.urls import path
from user_profile import views

app_name = 'profile'
urlpatterns = [
    path('', views.ProfileView.as_view(), name='user_profile'),
    path('<int:pk>/update/', views.UpdateProfileView.as_view(), name='user_update'),
]

src/books/models.py
from django.db import models
from reference_book.models import Author, Serie, Genre, Publisher

def upload(inst, filename):
    return f'book_picture/{inst.pk}-{filename}'


class BookCover(models.Model):
    book_cover = models.CharField(
        'Вид обложки',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_cover}'

class BookRestrictions(models.Model):
    book_restrictions = models.CharField(
        'Возрастные ограничения',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_restrictions}'

class BookAvailability(models.Model):
    book_availability = models.CharField(
        'Доступность книги',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_availability}'

class BookRating(models.Model):
    book_rating = models.CharField(
        'Рейтинг книги',
        max_length=50
    )

    def __str__(self):
        return f'{self.book_rating}'

class Book(models.Model):
    book_name = models.CharField(
        'Название книги',
        max_length=100
    )
    book_description = models.TextField(
        'Описание книги',
        blank=True,
        null=True
    )

    book_picture = models.ImageField(
        'Изображение обложки',
        upload_to=upload
    )

    book_price = models.DecimalField(
        'Цена книги(BYN)',
        default=0.0,
        max_digits=10,
        decimal_places=2
    )

    book_year = models.CharField(
        'Год издания',
        max_length=4
    )

    book_pages = models.CharField(
        'Количество страниц',
        max_length=5
    )

    book_cover = models.ForeignKey(
        BookCover,
        verbose_name='Вид обложки',
        on_delete=models.PROTECT,
        related_name='bookcover'
    )

    book_isbn = models.CharField(
        'ISBN',
        max_length=20
    )

    book_weight = models.CharField(
        'Вес в граммах',
        max_length=5
    )

    book_restrictions = models.ForeignKey(
        BookRestrictions,
        verbose_name='Возрастные ограничения',
        on_delete=models.PROTECT,
        related_name='bookrestrictions'
    )

    book_quantity = models.IntegerField(
        'Количество книг в наличии',
        default=0
    )
    
    book_availability = models.ForeignKey(
        BookAvailability,
        verbose_name='Доступность книги',
        on_delete=models.PROTECT,
        related_name='bookavailability'
    )

    book_rating = models.ForeignKey(
        BookRating,
        verbose_name='Рейтинг книги',
        on_delete=models.PROTECT,
        related_name='bookrating'
    )

    book_adding_date = models.DateTimeField(
        verbose_name='Дата внесения в каталог',
        auto_now=False,
        auto_now_add=True
    )

    book_updating_date = models.DateTimeField(
        verbose_name='Дата последнего изменения карточки',
        auto_now=True,
        auto_now_add=False
    )
    
    book_author = models.ManyToManyField(
        Author,
        verbose_name='Автор книги',
        related_name='book'
    )
    
    book_serie = models.ForeignKey(
        Serie,
        verbose_name='Серия книги',
        on_delete=models.PROTECT,
        related_name='book'
    )
    
    book_genre = models.ManyToManyField(
        Genre,
        verbose_name='Жанры',
        related_name='book'
    )
    
    book_publisher = models.ForeignKey(
        Publisher,
        verbose_name='Издательство',
        on_delete=models.PROTECT,
        related_name='book'
    )

    def __str__(self):
        return f'{self.book_name}'

src/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from user_profile.models import UserProfile
from books.models import Book

class Cart(models.Model):
    customer = models.ForeignKey(
        User,
        related_name='carts',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    created_date = models.DateTimeField(
        "Дата внесения в каталог", 
        auto_now=False, 
        auto_now_add=True
    )
    updated_date = models.DateTimeField(
        "Дата последнего изменения",
        auto_now=True,
        auto_now_add=False
    )

    def total_price(self):
        price = 0
        for book_in_cart in self.products.all():
            price += book_in_cart.price
        return price

    def __str__(self):
        return f"Корзина #{self.pk}"


class ProductInCart(models.Model):
    cart = models.ForeignKey(
        Cart,
        on_delete=models.CASCADE,
        related_name="products"
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.PROTECT,
        related_name='books_in_cart'
    )
    quantity = models.IntegerField(
        "Количество",
        default=1
    )
    price = models.DecimalField(
        "Цена",
        decimal_places=2,
        max_digits=7
    )

    @property
    def construct_price(self):
        price = self.quantity * self.book.book_price
        if price == 0:
            return 0
        return price

    def __str__(self):
        return f'Книга "{self.book.book_name}" в корзине #{self.cart.pk}, количество - {self.quantity}'
    class Meta:
        unique_together = (('cart', 'book'),)
    

src/orders/views.py
from django.views.generic import TemplateView, DeleteView, RedirectView
from orders import models
from books import models as book_models
from django.urls import reverse_lazy

def create_cart(user, session):
    cart = models.Cart.objects.create(customer=user)
    session['cart_id'] = cart.pk
    return cart

class CartView(TemplateView):
    template_name='orders/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        cart_id = self.request.session.get('cart_id')
        user = self.request.user

        if not isinstance(user, models.User):
            user = None
            
        if cart_id:
            cart = models.Cart.objects.filter(pk=cart_id).first()
            if not cart:
                cart = create_cart(user, self.request.session)
        else:
            cart = create_cart(user, self.request.session)
        context["cart"] = cart

       
        # add a book to the cart
        # check input
        book_id = self.request.GET.get('book')
        if not book_id:
            return context
        book = book_models.Book.objects.filter(pk=int(book_id)).first()
        if book:        
            book_in_cart, created = models.ProductInCart.objects.get_or_create(
                book=book,
                cart=cart,
                defaults={
                    'quantity': 1,
                    'price': book.book_price
                }
            )
            if not created:
                book_in_cart.quantity = book_in_cart.quantity + 1
                book_in_cart.price = book_in_cart.construct_price()
                book_in_cart.save()  
        else:
            pass # some redirect
        
        context["book"] = book
       
        return context

"""
class AddProducrToCartView(TemplateView):
    template_name = 'orders/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get('cart_id')
        user = self.request.user
        if not isinstance(user, models.User):
            user = None
        
        if cart_id:
            cart = models.Cart.objects.filter(pk=cart_id).first()
            if not cart:
                cart = create_cart(user, self.request.session)
        else:
            cart = create_cart(user, self.request.session)
        
        book_id = self.request.GET.get('book')
        book = book_models.Book.objects.filter(pk=book_id).first()

        if book:
            book_in_cart, created = models.ProductInCart.objects.get_or_create(
                book=book,
                cart=cart,
                defaults={
                    'quantity': 1,
                    'price': book.book_price
                }
            )

            if not created:
                book_in_cart.quantity = book_in_cart.quantity + 1
                book_in_cart.price = book_in_cart.construct_price()
                book_in_cart.save()

        context["cart"] = cart
        context["book"] = book

        return context
"""
    

class DeleteBookInCart(DeleteView):
    model = models.ProductInCart
    template_name='orders/delete-book-in-cart.html'
    success_url = reverse_lazy('orders:cart')

class CartUpdateView(RedirectView):
    def get_redirect_url(self):
        cart_id = self.request.session.get('cart_id')
        user = self.request.user
        if cart_id:
            cart = models.Cart.objects.filter(pk=cart_id).first()
        else:
            # redirect to error page
            pass
        button = self.request.POST.get('submit_button')
        if button == 'edit':
            obj_list = []
            for book_in_cart_id, quantity in self.request.POST.items():
                if book_in_cart_id not in ['csrfmiddlewaretoken', 'submit_button']:
                    # some check needed
                    book_in_cart = models.ProductInCart.objects.get(pk=int(book_in_cart_id))
                    if book_in_cart.cart.pk == cart_id:
                        book_in_cart.quantity = int(quantity)
                        obj_list.append(book_in_cart)
            models.ProductInCart.objects.bulk_update(obj_list, ['quantity'])
        else:
            pass
            # checkout

    
        return reverse_lazy('orders:cart')

src/orders/templates/orders/add.html
{% extends "base.html" %}
{% load static %}
  {% block title %}<title>Добавление в корзину</title>{% endblock title %}
{% load crispy_forms_tags %}

        {% block books_active %}
          <a class="nav-link dropdown-toggle active" href="{% url 'refs/book_list' %}" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Книги</a>

          
          {% endblock books_active %}

    {% block main %}
    {% include "message.html" %}
     <div class=container>
     <h3>Добавление книги {{object.books}}</h3>
     <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}

        <input class="btn btn-primary" type="submit" value="ОК">
    <a class="btn btn-success" href="{% url 'orders:cart' %}" > Назад </a>
     </form>
    </div>

</body>
    {% endblock main %}
</html>

src/orders/templates/orders/buy_goods.html
{% extends 'customer_base.html' %}
{% load crispy_forms_filters %}
{% block title %}
    <title>Cart</title>
{% endblock title %}

{% block body %}
    {% if not user %}
        <h4>Гость</h4>
    {% else %}
        <h4>{{ user.username|title }}</h4>
    {% endif %}

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Название книги</th>
            <th scope="col">Количество</th>
            <th scope="col">Цена</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        {% for book_in_cart in order.cart.products.all %}
            <tr>
                <td>{{ book_in_cart.book.book_name }}</td>
                <td>{{ book_in_cart.quantity }}</td>
                <td>{{ book_in_cart.price }}</td>
                <td>
                    <a href="{% url 'orders:book-in-cart-del' book_in_cart.pk %}" class="btn btn-danger"</a>Удалить из заказа</td>
            </tr>
        {% endfor %}
    </table>

    <h6>Total price: {{ order.cart.total_price }}</h6>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }} 
        <a href="{% url 'profile:user_profile' %}" class="btn btn-success" type="submit">Подтвердить заказ</a>
    </form>

{% endblock body %}

src/orders/templates/orders/cart.html
{% extends 'customer_base.html' %}
{% load static %}

{% block title %}
Корзина
{% endblock title %}

{% block body %}
    <h1>Cart</h1>
    Cart ID: {{ cart.pk }}<br>
    You have just added: {{ book.pk }} {{ book.book_name }}<br>
<hr>
<form action="{% url 'orders:cart-update' %}" method="post">
    {% csrf_token %}
<table class="table"> 
        {% for book_in_cart in cart.products.all %}
        <tr>
            <td>"{{ book_in_cart.book.book_name }}"</td> 
            <td><input type="number" class="form-control-sm" name="{{ book_in_cart.pk }}" id="" value="{{ book_in_cart.quantity }}"> шт.
                <small class="form-text text-muted">
                    Введите количество
                </small>
            </td>
            <td>Цена - {{ book_in_cart.price }} BYN</td>
            <td><a href="{% url 'orders:book-in-cart-del' book_in_cart.pk %}"><i class="fas fa-trash-alt"></i></a></td>
        </tr>
        {% endfor %} 
        
</table>
        <a href="{% url 'conf_order:create_order'%}" type="submit" class="btn btn-success" value="checkout">Подтвердить заказ</a>
        <button name="submit_button" type="submit" class="btn btn-primary" value="edit">Редактировать заказ</button>  
</form>
<hr>
Цена итого: {{ cart.total_price }} BYN
{% endblock body %} 

src/orders/templates/orders/delete-book-in-cart.html
{% extends 'customer_base.html' %}
{% load static %}

{% block title %}
Удалить товар из корзины
{% endblock title %}

{% block body %}
    <h1>Вы уверены, что хотите удалить "{{ object.book.book_name }}"?</h1>
    <form action="" method="post">{% csrf_token %}<button type="submit" class="btn btn-danger">Подтвердить</button></form>
{% endblock body %} 

src/orders/templates/orders/middle.html
  
{% extends 'customer_base.html' %}

{% block title %}
<title>Спасибо за заказ</title>
{% endblock title %}

{% block body %}
<h3>Благодарим Вас за заказ</h3>
<h6>Наш оператор скоро свяжется с Вами</h6>
<a href="{% url 'profile:user_profile' %}">Продолжить</a> 
{% endblock body %}